---
name: Trestle-bot autosync profile updates

on:
  pull_request:
    branches:
      - main
    paths:
      - 'profiles/**'
      - 'markdown/profiles/**'

jobs:
  autosync:
    name: Autosync profile content
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Run autosync
        id: autosync
        uses: RedHatProductSecurity/trestle-bot/actions/autosync@main
        with:
          markdown_path: "markdown/profiles"
          oscal_model: "profile"
          file_pattern: "*.json,markdown/*"
          branch: ${{ github.head_ref }}
