version: 2
updates:

  - package-ecosystem: "github-actions"
    directories:
      - '/'
      - '/.github/actions/e2e-testing'
      - '/.github/actions/publish-image'
      - '/.github/actions/setup-poetry'
    schedule:
      interval: "daily"
    commit-message:
      prefix: ":arrow_up:"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: ":arrow_up:"