
ENABLE_LINTERS:
  - REPOSITORY_GITLEAKS
  - REPOSITORY_KICS
  - ACTION_ACTIONLINT
  - MARKDOWN_MARKDOWNLINT
  - MAKEFILE_CHECKMAKE

DISABLE_ERRORS_LINTERS:
  - MAKEFILE_CHECKMAKE
  - BASH_SHELLCHECK

REPOSITORY_KICS_ARGUMENTS: "--fail-on high"