repos:
  - repo: https://github.com/returntocorp/semgrep
    rev: v1.51.0
    hooks:
      - id: semgrep
        name: Semgrep Python
        types: [python]
        args: ["--config", "p/python", "--error", --metrics=off]
      - id: semgrep
        name: Semgrep Bandit
        types: [python]
        exclude: "^tests/.+$"
        args: ["--config", "p/bandit", "--error", --metrics=off]
  - repo: local
    hooks:
      - id: lint
        language: system
        name: Check formatting and lint
        entry: make lint
        stages: [commit]
        types: [python]