name: "publish-image"
description: "Composite action to publish trestle-bot images."

inputs:
  image:
    required: true
    description: The image repository location in the format of registry/name/app
  release_version:
    required: true
    description: The version to build type semver tags from
  git_ref:
    required: true
    description: The git reference to build image from
  no_cache:
    description: Skip using cache when building the image.
    required: false
    default: "false"
  skip_tests:
    description: Skip pre-push testing
    required: false
    default: "false"
outputs:
  image_sha:
    value: ${{ inputs.image }}@${{ steps.build-and-push.outputs.digest }}
    description: The published image with digest

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # pin@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # pin@v3

    # Tags are defined here based on workflow triggers
    - name: Define metadata
      id: meta
      uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # pin@v5
      with:
        images: ${{ inputs.image }}
        tags: |
          type=semver,pattern=v{{major}},enable=${{ !startsWith(inputs.release_version, 'v0.') }},value=${{ inputs.release_version }}
          type=semver,pattern=v{{major}}.{{minor}},value=${{ inputs.release_version }}
          type=semver,pattern=v{{version}},value=${{ inputs.release_version }}
          type=raw,value=${{ inputs.release_version }}-{{branch}}-{{sha}},enable=${{ github.event_name == 'workflow_dispatch' }}
          type=schedule,pattern={{date 'YYYYMMDD'}},prefix=${{ inputs.release_version }}.
        flavor: |
          latest=false

    - name: Build and export to Docker
      uses: docker/build-push-action@1a162644f9a7e87d8f4b053101d1d9a712edc18c # pin@v5
      id: build-and-export
      with:
        context: "${{ github.server_url }}/${{ github.repository }}.git#${{ inputs.git_ref }}"
        load: true
        no-cache: ${{ inputs.no_cache == 'true' }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Pre-push Image Scan
      uses: aquasecurity/trivy-action@d710430a6722f083d3b36b8339ff66b32f22ee55 # pin@0.19.0
      with:
        image-ref: ${{ inputs.image }}:${{ steps.meta.outputs.version }}
        exit-code: 1
        skip-files: "**/.venv/lib/**/METADATA"
        scanners: secret
        severity: HIGH,CRITICAL,MEDIUM

    - name: Pre-push testing
      if: ${{ inputs.skip_tests == 'false' }}
      uses: ./.github/actions/e2e-testing
      with:
        image: "docker-daemon:${{ inputs.image }}:${{ steps.meta.outputs.version }}"
        build: false

    # Does not rebuild. Uses internal cache from previous step.
    - name: Build and Push
      uses: docker/build-push-action@1a162644f9a7e87d8f4b053101d1d9a712edc18c # pin@v5
      id: build-and-push
      with:
        context: "${{ github.server_url }}/${{ github.repository }}.git#${{ inputs.git_ref }}"
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
