---
name: Trestle-bot autosync profile updates

on:
  push:
    branches:
      - main
    paths:
      - 'profiles/**'
      - 'markdown/profiles/**'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  autosync:
    name: Autosync profile content
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run autosync
        id: autosync
        uses: RedHatProductSecurity/trestle-bot/actions/autosync@main
        with:
          markdown_path: "markdown/profiles"
          oscal_model: "profile"
          file_pattern: "*.json,markdown/*"
