---
name: Trestle-bot rules-transform and autosync

on:
  push:
    branches:
      - main
    paths:
      - 'profiles/**'
      - 'catalogs/**'
      - 'component-definitions/**'
      - 'markdown/**'
      - 'rules/**'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  rules-transform-and-autosync:
    name: Rules Transform and AutoSync
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: AutoSync
        id: autosync
        uses: RedHatProductSecurity/trestle-bot/actions/autosync@main
        with:
          markdown_path: "markdown/component-definitions"
          oscal_model: "compdef"
          file_pattern: "*.json,markdown/*"
      - name: Check if rules changed
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            rules:
              - 'rules/**'
      - name: Rules Transform
        if: steps.changes.outputs.rules == 'true'
        uses: RedHatProductSecurity/trestle-bot/actions/rules-transform@main
        with:
          markdown_path: "markdown/component-definitions"
          commit_message: "Auto-transform rules [skip ci]"