name: publish-docs
on:
  push:
    branches:
      - main
    paths:
      - 'mkdocs.yml'
      - 'docs/**'

permissions:
  contents: write

jobs:
  gh-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # pin@v4
      - uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f  # pin@v5
        with:
          python-version: '3.11'
      - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9  # pin@v4
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
